# Usar la imagen oficial de MySQL
FROM mysql:8.0

# Configurar variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=taller_db
ENV MYSQL_USER=taller_user
ENV MYSQL_PASSWORD=taller_password


# Exponer el puerto de MySQL
EXPOSE 3306
